import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-tl  from-black via-zinc-950 to-black">
        {children}
      </body>
    </html>
  );
}
